import zipfile
import main_program as mprog

import win32com.client as win32

A = [720, 830, 890, 940, 1050, 1160, 1300, 1480, 1560, 1760]
A_15 = [1080, 1245, 1335, 1410, 1575, 1740, 1950, 2220, 2340, 2640]
B = [1058, 1125, 1210, 1315, 1480, 1680, 1985, 2113, 2400, 2700]
B_15 = [1587, 1688, 1815, 1973, 2220, 2520, 2978, 3170, 3600, 4050]
H = [2060, 2185, 2290, 2540, 2755, 2990, 3270, 3725, 4005, 4285]
R = [388, 486, 516, 544, 614, 670, 730, 900, 970, 1040]
R_15 = [582, 729, 774, 816, 921, 1005, 1095, 1350, 1455, 1560]
E = [700, 780, 840, 900, 1050, 1150, 1250, 1400, 1500, 1600]
E_15 = [1051, 1170, 1260, 1350, 1575, 1725, 1875, 2100, 2250, 2400]
D_DH = [250, 280, 330, 350, 380, 430, 490, 550, 580, 610]
D_S = [80, 90, 110, 130, 150, 180, 200, 220, 250, 280]
D_H = [50, 60, 70, 80, 100, 110, 130, 150, 180, 210]
D_P = [35, 40, 45, 50, 60, 70, 80, 90, 100, 110]
DH_S = [230, 250, 270, 300, 330, 350, 400, 450, 450, 500]
DH_H = [200, 220, 240, 270, 300, 320, 360, 400, 400, 450]
DH_P = [200, 220, 240, 270, 300, 320, 360, 400, 400, 450]
S = [983, 1068, 1158, 1285, 1445, 1630, 1809, 2067, 2262, 2357]
H_Z = [1260, 1385, 1490, 1640, 1855, 2086.933, 2370, 2725, 3005, 3285]
O = [1045, 1075, 1125, 1145, 1175, 1225, 1285, 1345, 1375, 1405]
hole_type = [0, 1, 2]
P = [330, 380, 430, 480, 560, 650, 720, 860, 960, 1060]
P_15 = [495, 570, 645, 721, 840, 975, 1080, 1290, 1440, 1590]
Q = [250, 300, 350, 400, 460, 520, 580, 650, 720, 790]
Q_15 = [375, 450, 525, 600, 690, 780, 870, 975, 1080, 1185]
T = [85, 100, 115, 130, 140, 155, 165, 180, 180, 200]
Z = [800, 800, 800, 900, 900, 900, 900, 1000, 1000, 1100]
F = [320, 400, 440, 520, 600, 680, 760, 840, 900, 960]
FRAME20_H = [280, 355, 420, 437.5, 550, 680, 825, 990, 1120, 1170]
FRAME2_lower_depth = [166.016, 246.016, 286.016, 366.016, 446.016, 526.016, 606.016, 686.016, 746.016, 806.016]
FRAME2_lower_depth_15 = [331.016, 451.016, 511.016, 631.016, 751.016, 871.016, 991.016, 1111.016, 1201.016, 1291.016]
FRAME1_lower_high = [1330, 1335, 1340, 1445, 1455, 1460, 1470, 1575, 1595, 1695]
FRAME20_FRAME2_YZ = [805, 805, 979, 979, 979, 979, 979, 979, 979, 979]
BALANCER1_XZ = [204, 253, 268, 282, 317, 345, 375, 460, 575, 690]  # (R+180mm)/2+80mm
FRAME_10_H = [558, 620.5, 673, 798, 905.5, 1023, 1163, 1320.5, 1530.5, 1740.5]
FRAME_32_XY = [0, 0, 0, 1722, 1819.5, 1922, 2052, 2294.5, 2504.5, 2794.5]
# BOM_list = {'1': ['01 ', '50', '1680x2910', 'SS400', '1', '1628.6', '如圖'],
#             '2': ['02 ', '50', '1680x2910', 'SS400', '1', '1628.6', '如圖'],
#             '3': ['03 ', '40', '850x1027', 'SS400', '1', '1626.6', '如圖'],
#             '4': ['04 ', '32', '850x1050', 'SS400', '1', '207.0', '如圖'],
#             '5': ['05 ', '22', '850x590', 'SS400', '1', '84.2', '如圖'],
#             '6': ['06 ', '40', '80x182', 'SS400', '2', '3.9', '如圖'],
#             '7': ['07 ', '50', '850x710', 'SS400', '1', '127.0', '如圖'],
#             '8': ['08 ', '22', '670x476', 'SS400', '1', '53.8', '如圖'],
#             '9': ['8-1', '22', '670x150', 'SS400', '2', '17.4', '如圖'],
#             '10': [' 9 ', ' 9 ', '協中:250x90x850(待加)L', 'SS400', '1', '28.5', '槽型鋼'],
#             '11': [' 9 ', ' 9 ', '協台:250x90x850(待加)L', 'SS400', '1', '29.4', '槽型鋼'],
#             '12': ['10 ', '45', '255x300', 'SS400', '2', '24.5', '如圖'],
#             '13': ['11 ', '125', 'φ270xφ170', 'SS400', '1', '33.9', '如圖'],
#             '14': ['12 ', '19', '670x429', 'SS400', '1', '42.0', '如圖'],
#             '15': ['13 ', '19', '48x74', 'SS400', '2', '0.4', '如圖'],
#             '16': ['14 ', '40', '105x150', 'SS400', '2', '4.9', '如圖'],
#             '17': ['15A ', '50', '40x150', 'SS400', '2', '2.1', '如圖'],
#             '18': ['15 ', '50', '40x150', 'SS400', '2', '2.3', '如圖'],
#             '19': ['16 ', '40', '105x150', 'SS400', '2', '4.8', '如圖'],
#             '20': ['18 ', '19', '145x290', 'SS400', '1', '6.2', '如圖'],
#             '21': ['19 ', '90', '960x1588', 'SS400', '2', '609.4', '如圖'],
#             '22': ['20 ', '19', '145x300', 'SS400', '1', '5.8', '如圖'],
#             '23': ['21 ', '53', '75x75', 'SS400', '1', '2.4', '如圖'],
#             '24': ['22 ', '50', '850x710', 'SS400', '1', '156.4', '如圖'],
#             '25': ['24 ', '60', '85x420', 'SS400', '2', '15.9', '如圖'],
#             '26': ['25 ', '75', '75x75', 'SS400', '5', '2.4', '如圖'],
#             '27': ['26 ', '35', '50x50', 'SS400', '2', '0.7', ''],
#             '28': ['27 ', '25', '460x280', 'SS400', '2', '25.2', '如圖'],
#             '29': ['29 ', '19', '140x80', 'SS400', '4', '1.2', '如圖'],
#             '30': ['30 ', '45', '243x300', 'SS400', '2', '0.9', ''],
#             '31': ['33 ', '6', 'L65x30x850', 'SS400', '1', '3.6', '如圖'],
#             '32': ['34 ', '60', 'φ50', 'SS400', '2', '0.9', ''],
#             '33': ['35 ', '50', '850x680', 'SS400', '1', '197.2', '如圖'],
#             '34': ['40 ', '22', '850x165', 'SS400', '1', '24.2', ''],
#             '35': ['41 ', '6','角鐵:50x50x180L', 'SS400', '1', '197.2', '如圖'],
#             '36': ['43 ', '32', '32x85', 'SS400', '1', '0.7', '如圖'],
#             '37': ['44 ', '62', 'φ30', 'SS400', '1', '0.3', '如圖']}
#
#
# BOM_list_name = []
# for i in BOM_list:
#     BOM_list_name.append(i)
#
# BOM_position = [918, 114]
# BOM_position_x = [865 + 99, 865 + 116, 865 + 130, 865 + 212.5, 865 + 242, 865 + 255, 865 + 280]
# BOM_position_Y = 12
#
# def bom_text_create():
#     catapp = win32.Dispatch('CATIA.Application')
#     drawingdocument = catapp.ActiveDocument
#     drawingsheets = drawingdocument.Sheets
#     drawingsheet = drawingsheets.Item('Sheet.1')
#     drawingview = drawingsheet.Views.Item('Background View')
#     drawingview = drawingview.Texts
#     # drawingview.Activate()
#     for i in BOM_list_name:
#         for j in range(0, 7):
#             DrawText = drawingview.Add(BOM_list[i][j], BOM_position_x[j], 120 + 12 * int(i)) # 線段長度
#             DrawText.SetFontName(0, 0, 'Arial Unicode MS (TrueType)')
#             DrawText.SetFontSize(0, 0, 5)  # 調整字體位置和大小(x, y, 字體大小).
#             DrawText.AnchorPosition = 2  # 文字框對其位置(TopL=1,MidL=2,BottomL=3,TopM=4,MidM=5,BottomM=6,TopR=7,MidR=8,BottomR=9)
#
# bom_text_create()
#
# def create_center_line(x_value_1, y_value_1, x_value_2, y_value_2):
#     catapp = win32.Dispatch('CATIA.Application')
#     drawingdocument = catapp.ActiveDocument
#     drawingsheets = drawingdocument.Sheets
#     drawingsheet = drawingsheets.Item('Sheet.1')
#     drawingviews = drawingsheet.Views
#     drawingview = drawingviews.Item('Background View')
#     drawingview.Activate()
#     factory2d = drawingview.Factory2D
#     dotted_line = factory2d.CreateLine(x_value_1, y_value_1, x_value_2, y_value_2)
#     dotted_line.Name = 'chain_line'
#     object = catapp.ActiveDocument.Selection
#     # object.Search('Name=chain_line,all')
#     vis = catapp.ActiveDocument.Selection.VisProperties
#     vis.SetRealLineType(2, 0.3)
#     vis.SetRealWidth(1, 0.13)
#
# # for i in BOM_list_name:
# #     create_center_line(960, 102 + 12 * int(i), 1169, 102 + 12 * int(i))
mprog.save_detail_drawing("C:\\Users\\USER\\Desktop\\SN1-80_9_13_52_13" , "Exploded_Views")
mprog.saveas("C:\\Users\\USER\\Desktop\\SN1-80_9_13_52_13", "Exploded_Views", ".pdf")
